name: Frontend-Kiosk

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"

  extrastep:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "extra step"

  deploy:
    runs-on: ubuntu-latest
    environment: test
    needs: extrastep
    steps:
      - run: echo "extra step"

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    environment: test
    steps:
      - run: echo "extra step"
